<<<<<<< HEAD
#easy_admin:
#    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User
=======
easy_admin:
   entities:
       # List the entity class name you want to manage 
        - App\Entity\Riser
        - App\Entity\Lending
        - App\Entity\JumpingTilt
        - App\Entity\RepairCommentary
        - App\Entity\State
        - App\Entity\Category

        
       
>>>>>>> 9edcf61... add all Entity in easyAdmin
