easy_admin:
    formats:
        date: 'd/m/Y'
    site_name: 'Gestion des paires d''échasses'
    list:
        actions: ['show']
    entities:
        Riser:
            class: App\Entity\Riser
            label: 'Utilisateur'
            help: 'Les utilisateur qui loue les paires d''échasses'
            new:
                title: 'Ajouter un utiliateur '
            list: 
                fields:
                    - 'id' 
                    - { property: 'firstname', label: 'Prénom' }
                    - { property: 'lastname', label: 'Nom' }
                    - { property: 'birthdate', label: 'Date de naissance' }
            form:
                fields:
                    - { property: 'firstname', label: 'Prénom' }
                    - { property: 'lastname', label: 'Nom' }
                    - { property: 'birthdate', label: 'Date de naissance' , type_options: { widget: 'single_text'} }
            show:
                fields:
                    - 'id' 
                    - { property: 'firstname', label: 'Prénom' }
                    - { property: 'lastname', label: 'Nom' }
                    - { property: 'birthdate', label: 'Date de naissance' }
                    - { property: 'lendings' , label: 'Locations' }
        Echasse: 
            class: App\Entity\JumpingTilt
            label: 'Paire d''Echasses'
            help: 'Les paires d''Echasses du club Riser Road'
            new:
                title: "Ajouter une paire d'echasse"
            list: 
                fields:
                    - 'id'
                    - { property: 'reference', label: 'Référence' }
                    - { property: 'description', label: 'Description' }
                    - { property: 'weight', label: 'Dureté des lames' }
                    - { property: 'state', label: 'Etat' }
                    - { property: 'category', label: 'Catégorie' }
                    - { property: 'storageArea', label: 'Lieu de stockage' }
                    - { property: 'model', label: 'Model' }
                    - { property: 'rubber', label: 'couleurs des tampons' }
            form:
                fields:
                    - { property: 'reference', label: 'Référence' }
                    - { property: 'description', label: 'Description' }
                    - { property: 'weight', label: 'Dureté des lames' }
                    - { property: 'state', label: 'Etat' }
                    - { property: 'category', label: 'Catégorie' }
                    - { property: 'storageArea', label: 'Lieu de stockage' }
                    - { property: 'model', label: 'Model' }
                    - { property: 'rubber', label: 'couleurs des tampons' }
            show:
                fields:
                    - { property: 'reference', label: 'Référence' }
                    - { property: 'description', label: 'Description' }
                    - { property: 'weight', label: 'Dureté des lames' }
                    - { property: 'state', label: 'Etat' }
                    - { property: 'category', label: 'Catégorie' }
                    - { property: 'storageArea', label: 'Lieu de stockage' }
                    - { property: 'model', label: 'Model' }
                    - { property: 'rubber', label: 'couleurs des tampons' }
                    - { property: 'lendings', label: 'Locations' }

        Location:
            class: App\Entity\Lending
            label: 'Location'
            help: 'les location loué'
            new: 
                title: 'Ajouter une location'
            list:
                fields:
                    - 'id'  
                    - { property: 'startDate', label: 'Début location' }
                    - { property: 'endDate', label: 'Fin location' }
                    - { property: 'riser', label: 'Loueur' }
                    - { property: 'jumpingTilt', label: 'paire d''échasse' }
                    - { property: 'status', label: 'Status' }
            form:
                fields:
                    - { property: 'startDate', label: 'Début location' }
                    - { property: 'endDate', label: 'Fin location' }
                    - { property: 'riser', label: 'Loueur' }
                    - { property: 'jumpingTilt', label: 'paire d''échasse' } 
                    - { property: 'status', label: 'Status' }  
            show:
                fields:
                    - 'id'
                    - { property: 'startDate', label: 'Début location' }
                    - { property: 'endDate', label: 'Fin location' }
                    - { property: 'riser', label: 'Loueur' }
                    - { property: 'jumpingTilt', label: 'paire d''échasse' } 
                    - { property: 'status', label: 'Status' }  

        Categories: 
            class: App\Entity\Category
            new:
                title: 'Ajouter une catégorie'
            list:
                fields:
                    - { property: 'name', label: 'Catégorie' }
            form:
                fields:
                    - { property: 'name', label: 'Catégorie' }
            show:
                fields:
                    - { property: 'name', label: 'Catégorie' }
                    - { property: 'jumpingTilts', label: 'Paires d''échasses' }
                    
        Etats: 
            class: App\Entity\State
            new: 
                title: 'Ajouter un etat'
            list: 
                fields:
                    - { property: 'name', label: 'Etats' }
            show:
                fields:
                    - { property: 'name', label: 'Etats' }
                    - { property: 'jumpingTilts', label: 'Paires d''échasses' }
            form:
                fields:
                    - { property: 'name', label: 'Etats' }

        Reparation:
            class: App\Entity\RepairCommentary
            new: 
                title: 'Ajouter un commentaire de réparation'
            list:
                fields:
                    - 'id'
                    - { property: 'jumpingTilt', label: 'paire d''échasse' }
                    - { property: 'repairDate', label: 'date de réparation' }
                    - { property: 'comment', label: 'réparation effectué' }
            form:
                fields:
                    - { property: 'jumpingTilt', label: 'paire d''échasse' }
                    - { property: 'repairDate', label: 'date de réparation' }
                    - { property: 'comment', label: 'réparation effectué' }
            show:
                fields:
                    - { property: 'jumpingTilt', label: 'paire d''échasse' }
                    - { property: 'repairDate', label: 'date de réparation' }
                    - { property: 'comment', label: 'réparation effectué' }

        Lieu:
            class: App\Entity\StorageArea
            new:
                title: 'ajouter un lieu de stockage'
            list:
                fields:
                    - { property: 'name', label: 'lieu de stockage' }
            form:
                fields: 
                    - { property: 'name', label: 'lieu de stockage' }
            show:
                fields: 
                    - { property: 'name', label: 'lieu de stockage' }
                    - { property: 'jumpingTilts', label: 'Paires d''échasses' }

        Model:
            class: App\Entity\ModelJumpingStilt
            new: 
                title: 'ajouter une marque de paire d''échasses'
            list: 
                fields:
                    - { property: 'name', label: 'Model' }
            form:
                fields: 
                    - { property: 'name', label: 'Model' }
            show:
                fields: 
                    - { property: 'name', label: 'Model' }
                    - { property: 'jumpingTilts', label: 'Paire d''échasses' }

        Semelle:
            class: App\Entity\Rubber
            list:
                actions: ['show', '-delete', '-edit' ]
                fields:
                    - { property: 'color', label: 'Semmele' }
                   
            show:
                action: ['-edit', '-delete' ]
                fields:
                    - { property: 'color', label: 'Semmele' }
                    - { property: 'jumpingTilts', label: 'Paire d''échasses' }
            form:
                fields:
                     - { property: 'jumpingTilts', label: 'Paire d''échasses' }
                
                    
