easy_admin:
    formats:
        date: 'd/m/Y'
    site_name: 'Gestion des paires d''échasses'
    entities:
        Riser:
            class: App\Entity\Riser
            label: 'Utilisateur'
            help: 'Les utilisteur qui loue les paires d''échasses'
            new:
                title: 'Ajouter un utiliateur '
            list: 
                fields:
                    - 'id' 
                    - { property: 'firstname', label: 'Prénom' }
                    - { property: 'lastname', label: 'Nom' }
                    - { property: 'birthdate', label: 'Date de naissance' }
            form:
                fields:
                    - { property: 'firstname', label: 'Prénom' }
                    - { property: 'lastname', label: 'Nom' }
                    - { property: 'birthdate', label: 'Date de naissance' , type_options: { widget: 'single_text'} }
            show:
                fields:
                    - 'id' 
                    - { property: 'firstname', label: 'Prénom' }
                    - { property: 'lastname', label: 'Nom' }
                    - { property: 'birthdate', label: 'Date de naissance' }
                    - { property: 'lendings' , label: 'Locations' }
        Echasse: 
            class: App\Entity\JumpingTilt
            label: 'Paire d''Echasses'
            help: 'Les paires d''Echasses du club Riser Road'
            new:
                title: "Ajouter une paire d'echasse"
            list: 
                fields:
                    - 'id'
                    - { property: 'reference', label: 'Référence' }
                    - { property: 'description', label: 'Description' }
                    - { property: 'weight', label: 'Dureté des lames' }
                    - { property: 'state', label: 'Etat' }
                    - { property: 'category', label: 'Catégorie' }
            form:
                fields:
                    - { property: 'reference', label: 'Référence' }
                    - { property: 'description', label: 'Description' }
                    - { property: 'weight', label: 'Dureté des lames' }
                    - { property: 'state', label: 'Etat' }
                    - { property: 'category', label: 'Catégorie' }
            show:
                fields:
                    - { property: 'reference', label: 'Référence' }
                    - { property: 'description', label: 'Description' }
                    - { property: 'weight', label: 'Dureté des lames' }
                    - { property: 'state', label: 'Etat' }
                    - { property: 'category', label: 'Catégorie' }
                    - { property: 'lendings', label: 'Locations' }

        Location:
            class: App\Entity\Lending
            label: 'Location'
            help: 'les location loué'
            new: 
                title: 'Ajouter une location'
            list:
                fields:
                    - 'id'  
                    - { property: 'startDate', label: 'Début location' }
                    - { property: 'endDate', label: 'Fin location' }
                    - { property: 'riser', label: 'Loueur' }
                    - { property: 'jumpingTilt', label: 'paire d''échasse' }
            form:
                fields:
                    - { property: 'startDate', label: 'Début location' }
                    - { property: 'endDate', label: 'Fin location' }
                    - { property: 'riser', label: 'Loueur' }
                    - { property: 'jumpingTilt', label: 'paire d''échasse' }   
            show:
                fields:
                    - 'id'
                    - { property: 'startDate', label: 'Début location' }
                    - { property: 'endDate', label: 'Fin location' }
                    - { property: 'riser', label: 'Loueur' }
                    - { property: 'jumpingTilt', label: 'paire d''échasse' }   

        Categories: 
            class: App\Entity\Category
            new:
                title: 'Ajouter une catégorie'
            list:
                fields:
                    - { property: 'name', label: 'Catégorie' }
            form:
                fields:
                    - { property: 'name', label: 'Catégorie' }
            show:
                fields:
                    - { property: 'name', label: 'Catégorie' }
                    - { property: 'jumpingTilts', label: 'Paires d''échasses' }
                    
        Etats: 
            class: App\Entity\State
            new: 
                title: 'Ajouter un etat'
            list: 
                fields:
                    - { property: 'name', label: 'Etats' }
            show:
                fields:
                    - { property: 'name', label: 'Etats' }
                    - { property: 'jumpingTilts', label: 'Paires d''échasses' }
                    
