easy_admin:
   entities:
       # List the entity class name you want to manage 
        Category: 
          class: App\Entity\Category
          form: 
            fields: 
                - 'name'
          list: 
            fields: 
                - 'Etat' 
        JumpingTilt:
            class: App\Entity\JumpingTilt
            list:
                fields: ['reference', 'description', 'weight', { property: 'state.name', label: 'State' }, { property: 'category.name', label: 'Category' } ]
            form:
              fields:
                - 'reference'
                - 'description'
                - 'weight'
                - { property: 'state', type: 'entity', type_options: { choice_label: 'state' }}
                - { property: 'category', type: 'entity', type_options: { choice_label: 'category' }}
        Riser: 
            class: App\Entity\Riser
            form:
              fields:
                - 'firstname'
                - 'lastname'
                - 'birthdate'
                - { property: 'lendings', type: 'entity', type_options: { choice_label: 'jumpingTilt.reference'}}
            list:
              fields: 
                - 'Prénom'
                - 'Nom' 
                - 'Date de naissance'
                - 'Locations echasse' 
       
